spring:
  profiles:
    active:
      development
  config:
    location: /src/main/resources/config
server:
  port: 8082
  servlet:
    context-path: /BsfLimites
banner:
  location: src/main/resources/config/banner.txt
logging:
  config: src/main/resources/config/logback-spring.xml